// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/auto-devs/auto-devs/internal/entity"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// AddAttachment provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) AddAttachment(ctx context.Context, attachment *entity.TaskAttachment) error {
	ret := _mock.Called(ctx, attachment)

	if len(ret) == 0 {
		panic("no return value specified for AddAttachment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TaskAttachment) error); ok {
		r0 = returnFunc(ctx, attachment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_AddAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAttachment'
type MockTaskRepository_AddAttachment_Call struct {
	*mock.Call
}

// AddAttachment is a helper method to define mock.On call
//   - ctx
//   - attachment
func (_e *MockTaskRepository_Expecter) AddAttachment(ctx interface{}, attachment interface{}) *MockTaskRepository_AddAttachment_Call {
	return &MockTaskRepository_AddAttachment_Call{Call: _e.mock.On("AddAttachment", ctx, attachment)}
}

func (_c *MockTaskRepository_AddAttachment_Call) Run(run func(ctx context.Context, attachment *entity.TaskAttachment)) *MockTaskRepository_AddAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.TaskAttachment))
	})
	return _c
}

func (_c *MockTaskRepository_AddAttachment_Call) Return(err error) *MockTaskRepository_AddAttachment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_AddAttachment_Call) RunAndReturn(run func(ctx context.Context, attachment *entity.TaskAttachment) error) *MockTaskRepository_AddAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// AddComment provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) AddComment(ctx context.Context, comment *entity.TaskComment) error {
	ret := _mock.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TaskComment) error); ok {
		r0 = returnFunc(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_AddComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddComment'
type MockTaskRepository_AddComment_Call struct {
	*mock.Call
}

// AddComment is a helper method to define mock.On call
//   - ctx
//   - comment
func (_e *MockTaskRepository_Expecter) AddComment(ctx interface{}, comment interface{}) *MockTaskRepository_AddComment_Call {
	return &MockTaskRepository_AddComment_Call{Call: _e.mock.On("AddComment", ctx, comment)}
}

func (_c *MockTaskRepository_AddComment_Call) Run(run func(ctx context.Context, comment *entity.TaskComment)) *MockTaskRepository_AddComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.TaskComment))
	})
	return _c
}

func (_c *MockTaskRepository_AddComment_Call) Return(err error) *MockTaskRepository_AddComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_AddComment_Call) RunAndReturn(run func(ctx context.Context, comment *entity.TaskComment) error) *MockTaskRepository_AddComment_Call {
	_c.Call.Return(run)
	return _c
}

// AddDependency provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) AddDependency(ctx context.Context, taskID uuid.UUID, dependsOnTaskID uuid.UUID, dependencyType string) error {
	ret := _mock.Called(ctx, taskID, dependsOnTaskID, dependencyType)

	if len(ret) == 0 {
		panic("no return value specified for AddDependency")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, taskID, dependsOnTaskID, dependencyType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_AddDependency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDependency'
type MockTaskRepository_AddDependency_Call struct {
	*mock.Call
}

// AddDependency is a helper method to define mock.On call
//   - ctx
//   - taskID
//   - dependsOnTaskID
//   - dependencyType
func (_e *MockTaskRepository_Expecter) AddDependency(ctx interface{}, taskID interface{}, dependsOnTaskID interface{}, dependencyType interface{}) *MockTaskRepository_AddDependency_Call {
	return &MockTaskRepository_AddDependency_Call{Call: _e.mock.On("AddDependency", ctx, taskID, dependsOnTaskID, dependencyType)}
}

func (_c *MockTaskRepository_AddDependency_Call) Run(run func(ctx context.Context, taskID uuid.UUID, dependsOnTaskID uuid.UUID, dependencyType string)) *MockTaskRepository_AddDependency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockTaskRepository_AddDependency_Call) Return(err error) *MockTaskRepository_AddDependency_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_AddDependency_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID, dependsOnTaskID uuid.UUID, dependencyType string) error) *MockTaskRepository_AddDependency_Call {
	_c.Call.Return(run)
	return _c
}

// BulkArchive provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) BulkArchive(ctx context.Context, taskIDs []uuid.UUID) error {
	ret := _mock.Called(ctx, taskIDs)

	if len(ret) == 0 {
		panic("no return value specified for BulkArchive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, taskIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_BulkArchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkArchive'
type MockTaskRepository_BulkArchive_Call struct {
	*mock.Call
}

// BulkArchive is a helper method to define mock.On call
//   - ctx
//   - taskIDs
func (_e *MockTaskRepository_Expecter) BulkArchive(ctx interface{}, taskIDs interface{}) *MockTaskRepository_BulkArchive_Call {
	return &MockTaskRepository_BulkArchive_Call{Call: _e.mock.On("BulkArchive", ctx, taskIDs)}
}

func (_c *MockTaskRepository_BulkArchive_Call) Run(run func(ctx context.Context, taskIDs []uuid.UUID)) *MockTaskRepository_BulkArchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_BulkArchive_Call) Return(err error) *MockTaskRepository_BulkArchive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_BulkArchive_Call) RunAndReturn(run func(ctx context.Context, taskIDs []uuid.UUID) error) *MockTaskRepository_BulkArchive_Call {
	_c.Call.Return(run)
	return _c
}

// BulkAssign provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) BulkAssign(ctx context.Context, taskIDs []uuid.UUID, assignedTo string) error {
	ret := _mock.Called(ctx, taskIDs, assignedTo)

	if len(ret) == 0 {
		panic("no return value specified for BulkAssign")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, taskIDs, assignedTo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_BulkAssign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkAssign'
type MockTaskRepository_BulkAssign_Call struct {
	*mock.Call
}

// BulkAssign is a helper method to define mock.On call
//   - ctx
//   - taskIDs
//   - assignedTo
func (_e *MockTaskRepository_Expecter) BulkAssign(ctx interface{}, taskIDs interface{}, assignedTo interface{}) *MockTaskRepository_BulkAssign_Call {
	return &MockTaskRepository_BulkAssign_Call{Call: _e.mock.On("BulkAssign", ctx, taskIDs, assignedTo)}
}

func (_c *MockTaskRepository_BulkAssign_Call) Run(run func(ctx context.Context, taskIDs []uuid.UUID, assignedTo string)) *MockTaskRepository_BulkAssign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockTaskRepository_BulkAssign_Call) Return(err error) *MockTaskRepository_BulkAssign_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_BulkAssign_Call) RunAndReturn(run func(ctx context.Context, taskIDs []uuid.UUID, assignedTo string) error) *MockTaskRepository_BulkAssign_Call {
	_c.Call.Return(run)
	return _c
}

// BulkDelete provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) BulkDelete(ctx context.Context, taskIDs []uuid.UUID) error {
	ret := _mock.Called(ctx, taskIDs)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, taskIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_BulkDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkDelete'
type MockTaskRepository_BulkDelete_Call struct {
	*mock.Call
}

// BulkDelete is a helper method to define mock.On call
//   - ctx
//   - taskIDs
func (_e *MockTaskRepository_Expecter) BulkDelete(ctx interface{}, taskIDs interface{}) *MockTaskRepository_BulkDelete_Call {
	return &MockTaskRepository_BulkDelete_Call{Call: _e.mock.On("BulkDelete", ctx, taskIDs)}
}

func (_c *MockTaskRepository_BulkDelete_Call) Run(run func(ctx context.Context, taskIDs []uuid.UUID)) *MockTaskRepository_BulkDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_BulkDelete_Call) Return(err error) *MockTaskRepository_BulkDelete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_BulkDelete_Call) RunAndReturn(run func(ctx context.Context, taskIDs []uuid.UUID) error) *MockTaskRepository_BulkDelete_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUnarchive provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) BulkUnarchive(ctx context.Context, taskIDs []uuid.UUID) error {
	ret := _mock.Called(ctx, taskIDs)

	if len(ret) == 0 {
		panic("no return value specified for BulkUnarchive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) error); ok {
		r0 = returnFunc(ctx, taskIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_BulkUnarchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUnarchive'
type MockTaskRepository_BulkUnarchive_Call struct {
	*mock.Call
}

// BulkUnarchive is a helper method to define mock.On call
//   - ctx
//   - taskIDs
func (_e *MockTaskRepository_Expecter) BulkUnarchive(ctx interface{}, taskIDs interface{}) *MockTaskRepository_BulkUnarchive_Call {
	return &MockTaskRepository_BulkUnarchive_Call{Call: _e.mock.On("BulkUnarchive", ctx, taskIDs)}
}

func (_c *MockTaskRepository_BulkUnarchive_Call) Run(run func(ctx context.Context, taskIDs []uuid.UUID)) *MockTaskRepository_BulkUnarchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_BulkUnarchive_Call) Return(err error) *MockTaskRepository_BulkUnarchive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_BulkUnarchive_Call) RunAndReturn(run func(ctx context.Context, taskIDs []uuid.UUID) error) *MockTaskRepository_BulkUnarchive_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUpdatePriority provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) BulkUpdatePriority(ctx context.Context, taskIDs []uuid.UUID, priority entity.TaskPriority) error {
	ret := _mock.Called(ctx, taskIDs, priority)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdatePriority")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, entity.TaskPriority) error); ok {
		r0 = returnFunc(ctx, taskIDs, priority)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_BulkUpdatePriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpdatePriority'
type MockTaskRepository_BulkUpdatePriority_Call struct {
	*mock.Call
}

// BulkUpdatePriority is a helper method to define mock.On call
//   - ctx
//   - taskIDs
//   - priority
func (_e *MockTaskRepository_Expecter) BulkUpdatePriority(ctx interface{}, taskIDs interface{}, priority interface{}) *MockTaskRepository_BulkUpdatePriority_Call {
	return &MockTaskRepository_BulkUpdatePriority_Call{Call: _e.mock.On("BulkUpdatePriority", ctx, taskIDs, priority)}
}

func (_c *MockTaskRepository_BulkUpdatePriority_Call) Run(run func(ctx context.Context, taskIDs []uuid.UUID, priority entity.TaskPriority)) *MockTaskRepository_BulkUpdatePriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID), args[2].(entity.TaskPriority))
	})
	return _c
}

func (_c *MockTaskRepository_BulkUpdatePriority_Call) Return(err error) *MockTaskRepository_BulkUpdatePriority_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_BulkUpdatePriority_Call) RunAndReturn(run func(ctx context.Context, taskIDs []uuid.UUID, priority entity.TaskPriority) error) *MockTaskRepository_BulkUpdatePriority_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUpdateStatus provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) BulkUpdateStatus(ctx context.Context, ids []uuid.UUID, status entity.TaskStatus, changedBy *string) error {
	ret := _mock.Called(ctx, ids, status, changedBy)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, entity.TaskStatus, *string) error); ok {
		r0 = returnFunc(ctx, ids, status, changedBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_BulkUpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpdateStatus'
type MockTaskRepository_BulkUpdateStatus_Call struct {
	*mock.Call
}

// BulkUpdateStatus is a helper method to define mock.On call
//   - ctx
//   - ids
//   - status
//   - changedBy
func (_e *MockTaskRepository_Expecter) BulkUpdateStatus(ctx interface{}, ids interface{}, status interface{}, changedBy interface{}) *MockTaskRepository_BulkUpdateStatus_Call {
	return &MockTaskRepository_BulkUpdateStatus_Call{Call: _e.mock.On("BulkUpdateStatus", ctx, ids, status, changedBy)}
}

func (_c *MockTaskRepository_BulkUpdateStatus_Call) Run(run func(ctx context.Context, ids []uuid.UUID, status entity.TaskStatus, changedBy *string)) *MockTaskRepository_BulkUpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID), args[2].(entity.TaskStatus), args[3].(*string))
	})
	return _c
}

func (_c *MockTaskRepository_BulkUpdateStatus_Call) Return(err error) *MockTaskRepository_BulkUpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_BulkUpdateStatus_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID, status entity.TaskStatus, changedBy *string) error) *MockTaskRepository_BulkUpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// CheckDuplicateTitle provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) CheckDuplicateTitle(ctx context.Context, projectID uuid.UUID, title string, excludeID *uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, projectID, title, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for CheckDuplicateTitle")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, projectID, title, excludeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, *uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, projectID, title, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectID, title, excludeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_CheckDuplicateTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckDuplicateTitle'
type MockTaskRepository_CheckDuplicateTitle_Call struct {
	*mock.Call
}

// CheckDuplicateTitle is a helper method to define mock.On call
//   - ctx
//   - projectID
//   - title
//   - excludeID
func (_e *MockTaskRepository_Expecter) CheckDuplicateTitle(ctx interface{}, projectID interface{}, title interface{}, excludeID interface{}) *MockTaskRepository_CheckDuplicateTitle_Call {
	return &MockTaskRepository_CheckDuplicateTitle_Call{Call: _e.mock.On("CheckDuplicateTitle", ctx, projectID, title, excludeID)}
}

func (_c *MockTaskRepository_CheckDuplicateTitle_Call) Run(run func(ctx context.Context, projectID uuid.UUID, title string, excludeID *uuid.UUID)) *MockTaskRepository_CheckDuplicateTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(*uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_CheckDuplicateTitle_Call) Return(b bool, err error) *MockTaskRepository_CheckDuplicateTitle_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTaskRepository_CheckDuplicateTitle_Call) RunAndReturn(run func(ctx context.Context, projectID uuid.UUID, title string, excludeID *uuid.UUID) (bool, error)) *MockTaskRepository_CheckDuplicateTitle_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Create(ctx context.Context, task *entity.Task) error {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Task) error); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - task
func (_e *MockTaskRepository_Expecter) Create(ctx interface{}, task interface{}) *MockTaskRepository_Create_Call {
	return &MockTaskRepository_Create_Call{Call: _e.mock.On("Create", ctx, task)}
}

func (_c *MockTaskRepository_Create_Call) Run(run func(ctx context.Context, task *entity.Task)) *MockTaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Task))
	})
	return _c
}

func (_c *MockTaskRepository_Create_Call) Return(err error) *MockTaskRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Create_Call) RunAndReturn(run func(ctx context.Context, task *entity.Task) error) *MockTaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAuditLog provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) CreateAuditLog(ctx context.Context, auditLog *entity.TaskAuditLog) error {
	ret := _mock.Called(ctx, auditLog)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuditLog")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TaskAuditLog) error); ok {
		r0 = returnFunc(ctx, auditLog)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_CreateAuditLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuditLog'
type MockTaskRepository_CreateAuditLog_Call struct {
	*mock.Call
}

// CreateAuditLog is a helper method to define mock.On call
//   - ctx
//   - auditLog
func (_e *MockTaskRepository_Expecter) CreateAuditLog(ctx interface{}, auditLog interface{}) *MockTaskRepository_CreateAuditLog_Call {
	return &MockTaskRepository_CreateAuditLog_Call{Call: _e.mock.On("CreateAuditLog", ctx, auditLog)}
}

func (_c *MockTaskRepository_CreateAuditLog_Call) Run(run func(ctx context.Context, auditLog *entity.TaskAuditLog)) *MockTaskRepository_CreateAuditLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.TaskAuditLog))
	})
	return _c
}

func (_c *MockTaskRepository_CreateAuditLog_Call) Return(err error) *MockTaskRepository_CreateAuditLog_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_CreateAuditLog_Call) RunAndReturn(run func(ctx context.Context, auditLog *entity.TaskAuditLog) error) *MockTaskRepository_CreateAuditLog_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTaskFromTemplate provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) CreateTaskFromTemplate(ctx context.Context, templateID uuid.UUID, projectID uuid.UUID, createdBy string) (*entity.Task, error) {
	ret := _mock.Called(ctx, templateID, projectID, createdBy)

	if len(ret) == 0 {
		panic("no return value specified for CreateTaskFromTemplate")
	}

	var r0 *entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*entity.Task, error)); ok {
		return returnFunc(ctx, templateID, projectID, createdBy)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *entity.Task); ok {
		r0 = returnFunc(ctx, templateID, projectID, createdBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, templateID, projectID, createdBy)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_CreateTaskFromTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTaskFromTemplate'
type MockTaskRepository_CreateTaskFromTemplate_Call struct {
	*mock.Call
}

// CreateTaskFromTemplate is a helper method to define mock.On call
//   - ctx
//   - templateID
//   - projectID
//   - createdBy
func (_e *MockTaskRepository_Expecter) CreateTaskFromTemplate(ctx interface{}, templateID interface{}, projectID interface{}, createdBy interface{}) *MockTaskRepository_CreateTaskFromTemplate_Call {
	return &MockTaskRepository_CreateTaskFromTemplate_Call{Call: _e.mock.On("CreateTaskFromTemplate", ctx, templateID, projectID, createdBy)}
}

func (_c *MockTaskRepository_CreateTaskFromTemplate_Call) Run(run func(ctx context.Context, templateID uuid.UUID, projectID uuid.UUID, createdBy string)) *MockTaskRepository_CreateTaskFromTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(string))
	})
	return _c
}

func (_c *MockTaskRepository_CreateTaskFromTemplate_Call) Return(task *entity.Task, err error) *MockTaskRepository_CreateTaskFromTemplate_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskRepository_CreateTaskFromTemplate_Call) RunAndReturn(run func(ctx context.Context, templateID uuid.UUID, projectID uuid.UUID, createdBy string) (*entity.Task, error)) *MockTaskRepository_CreateTaskFromTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTemplate provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) CreateTemplate(ctx context.Context, template *entity.TaskTemplate) error {
	ret := _mock.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for CreateTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TaskTemplate) error); ok {
		r0 = returnFunc(ctx, template)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_CreateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTemplate'
type MockTaskRepository_CreateTemplate_Call struct {
	*mock.Call
}

// CreateTemplate is a helper method to define mock.On call
//   - ctx
//   - template
func (_e *MockTaskRepository_Expecter) CreateTemplate(ctx interface{}, template interface{}) *MockTaskRepository_CreateTemplate_Call {
	return &MockTaskRepository_CreateTemplate_Call{Call: _e.mock.On("CreateTemplate", ctx, template)}
}

func (_c *MockTaskRepository_CreateTemplate_Call) Run(run func(ctx context.Context, template *entity.TaskTemplate)) *MockTaskRepository_CreateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.TaskTemplate))
	})
	return _c
}

func (_c *MockTaskRepository_CreateTemplate_Call) Return(err error) *MockTaskRepository_CreateTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_CreateTemplate_Call) RunAndReturn(run func(ctx context.Context, template *entity.TaskTemplate) error) *MockTaskRepository_CreateTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockTaskRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTaskRepository_Delete_Call {
	return &MockTaskRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTaskRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_Delete_Call) Return(err error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAttachment provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) DeleteAttachment(ctx context.Context, attachmentID uuid.UUID) error {
	ret := _mock.Called(ctx, attachmentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAttachment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, attachmentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_DeleteAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAttachment'
type MockTaskRepository_DeleteAttachment_Call struct {
	*mock.Call
}

// DeleteAttachment is a helper method to define mock.On call
//   - ctx
//   - attachmentID
func (_e *MockTaskRepository_Expecter) DeleteAttachment(ctx interface{}, attachmentID interface{}) *MockTaskRepository_DeleteAttachment_Call {
	return &MockTaskRepository_DeleteAttachment_Call{Call: _e.mock.On("DeleteAttachment", ctx, attachmentID)}
}

func (_c *MockTaskRepository_DeleteAttachment_Call) Run(run func(ctx context.Context, attachmentID uuid.UUID)) *MockTaskRepository_DeleteAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_DeleteAttachment_Call) Return(err error) *MockTaskRepository_DeleteAttachment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_DeleteAttachment_Call) RunAndReturn(run func(ctx context.Context, attachmentID uuid.UUID) error) *MockTaskRepository_DeleteAttachment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) DeleteComment(ctx context.Context, commentID uuid.UUID) error {
	ret := _mock.Called(ctx, commentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, commentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockTaskRepository_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx
//   - commentID
func (_e *MockTaskRepository_Expecter) DeleteComment(ctx interface{}, commentID interface{}) *MockTaskRepository_DeleteComment_Call {
	return &MockTaskRepository_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, commentID)}
}

func (_c *MockTaskRepository_DeleteComment_Call) Run(run func(ctx context.Context, commentID uuid.UUID)) *MockTaskRepository_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_DeleteComment_Call) Return(err error) *MockTaskRepository_DeleteComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_DeleteComment_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID) error) *MockTaskRepository_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTemplate provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) DeleteTemplate(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_DeleteTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTemplate'
type MockTaskRepository_DeleteTemplate_Call struct {
	*mock.Call
}

// DeleteTemplate is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockTaskRepository_Expecter) DeleteTemplate(ctx interface{}, id interface{}) *MockTaskRepository_DeleteTemplate_Call {
	return &MockTaskRepository_DeleteTemplate_Call{Call: _e.mock.On("DeleteTemplate", ctx, id)}
}

func (_c *MockTaskRepository_DeleteTemplate_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskRepository_DeleteTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_DeleteTemplate_Call) Return(err error) *MockTaskRepository_DeleteTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_DeleteTemplate_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockTaskRepository_DeleteTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// ExportTasks provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) ExportTasks(ctx context.Context, filters entity.TaskFilters, format entity.TaskExportFormat) ([]byte, error) {
	ret := _mock.Called(ctx, filters, format)

	if len(ret) == 0 {
		panic("no return value specified for ExportTasks")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.TaskFilters, entity.TaskExportFormat) ([]byte, error)); ok {
		return returnFunc(ctx, filters, format)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.TaskFilters, entity.TaskExportFormat) []byte); ok {
		r0 = returnFunc(ctx, filters, format)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.TaskFilters, entity.TaskExportFormat) error); ok {
		r1 = returnFunc(ctx, filters, format)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_ExportTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportTasks'
type MockTaskRepository_ExportTasks_Call struct {
	*mock.Call
}

// ExportTasks is a helper method to define mock.On call
//   - ctx
//   - filters
//   - format
func (_e *MockTaskRepository_Expecter) ExportTasks(ctx interface{}, filters interface{}, format interface{}) *MockTaskRepository_ExportTasks_Call {
	return &MockTaskRepository_ExportTasks_Call{Call: _e.mock.On("ExportTasks", ctx, filters, format)}
}

func (_c *MockTaskRepository_ExportTasks_Call) Run(run func(ctx context.Context, filters entity.TaskFilters, format entity.TaskExportFormat)) *MockTaskRepository_ExportTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.TaskFilters), args[2].(entity.TaskExportFormat))
	})
	return _c
}

func (_c *MockTaskRepository_ExportTasks_Call) Return(bytes []byte, err error) *MockTaskRepository_ExportTasks_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockTaskRepository_ExportTasks_Call) RunAndReturn(run func(ctx context.Context, filters entity.TaskFilters, format entity.TaskExportFormat) ([]byte, error)) *MockTaskRepository_ExportTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetArchivedTasks provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetArchivedTasks(ctx context.Context, projectID *uuid.UUID) ([]*entity.Task, error) {
	ret := _mock.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetArchivedTasks")
	}

	var r0 []*entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID) ([]*entity.Task, error)); ok {
		return returnFunc(ctx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID) []*entity.Task); ok {
		r0 = returnFunc(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetArchivedTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetArchivedTasks'
type MockTaskRepository_GetArchivedTasks_Call struct {
	*mock.Call
}

// GetArchivedTasks is a helper method to define mock.On call
//   - ctx
//   - projectID
func (_e *MockTaskRepository_Expecter) GetArchivedTasks(ctx interface{}, projectID interface{}) *MockTaskRepository_GetArchivedTasks_Call {
	return &MockTaskRepository_GetArchivedTasks_Call{Call: _e.mock.On("GetArchivedTasks", ctx, projectID)}
}

func (_c *MockTaskRepository_GetArchivedTasks_Call) Run(run func(ctx context.Context, projectID *uuid.UUID)) *MockTaskRepository_GetArchivedTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetArchivedTasks_Call) Return(tasks []*entity.Task, err error) *MockTaskRepository_GetArchivedTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_GetArchivedTasks_Call) RunAndReturn(run func(ctx context.Context, projectID *uuid.UUID) ([]*entity.Task, error)) *MockTaskRepository_GetArchivedTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttachments provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetAttachments(ctx context.Context, taskID uuid.UUID) ([]*entity.TaskAttachment, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetAttachments")
	}

	var r0 []*entity.TaskAttachment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.TaskAttachment, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.TaskAttachment); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TaskAttachment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetAttachments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttachments'
type MockTaskRepository_GetAttachments_Call struct {
	*mock.Call
}

// GetAttachments is a helper method to define mock.On call
//   - ctx
//   - taskID
func (_e *MockTaskRepository_Expecter) GetAttachments(ctx interface{}, taskID interface{}) *MockTaskRepository_GetAttachments_Call {
	return &MockTaskRepository_GetAttachments_Call{Call: _e.mock.On("GetAttachments", ctx, taskID)}
}

func (_c *MockTaskRepository_GetAttachments_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockTaskRepository_GetAttachments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetAttachments_Call) Return(taskAttachments []*entity.TaskAttachment, err error) *MockTaskRepository_GetAttachments_Call {
	_c.Call.Return(taskAttachments, err)
	return _c
}

func (_c *MockTaskRepository_GetAttachments_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) ([]*entity.TaskAttachment, error)) *MockTaskRepository_GetAttachments_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuditLogs provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetAuditLogs(ctx context.Context, taskID uuid.UUID, limit *int) ([]*entity.TaskAuditLog, error) {
	ret := _mock.Called(ctx, taskID, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAuditLogs")
	}

	var r0 []*entity.TaskAuditLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *int) ([]*entity.TaskAuditLog, error)); ok {
		return returnFunc(ctx, taskID, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *int) []*entity.TaskAuditLog); ok {
		r0 = returnFunc(ctx, taskID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TaskAuditLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *int) error); ok {
		r1 = returnFunc(ctx, taskID, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetAuditLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuditLogs'
type MockTaskRepository_GetAuditLogs_Call struct {
	*mock.Call
}

// GetAuditLogs is a helper method to define mock.On call
//   - ctx
//   - taskID
//   - limit
func (_e *MockTaskRepository_Expecter) GetAuditLogs(ctx interface{}, taskID interface{}, limit interface{}) *MockTaskRepository_GetAuditLogs_Call {
	return &MockTaskRepository_GetAuditLogs_Call{Call: _e.mock.On("GetAuditLogs", ctx, taskID, limit)}
}

func (_c *MockTaskRepository_GetAuditLogs_Call) Run(run func(ctx context.Context, taskID uuid.UUID, limit *int)) *MockTaskRepository_GetAuditLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*int))
	})
	return _c
}

func (_c *MockTaskRepository_GetAuditLogs_Call) Return(taskAuditLogs []*entity.TaskAuditLog, err error) *MockTaskRepository_GetAuditLogs_Call {
	_c.Call.Return(taskAuditLogs, err)
	return _c
}

func (_c *MockTaskRepository_GetAuditLogs_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID, limit *int) ([]*entity.TaskAuditLog, error)) *MockTaskRepository_GetAuditLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Task, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Task, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Task); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTaskRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockTaskRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTaskRepository_GetByID_Call {
	return &MockTaskRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTaskRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) Return(task *entity.Task, err error) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.Task, error)) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProjectID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetByProjectID(ctx context.Context, projectID uuid.UUID) ([]*entity.Task, error) {
	ret := _mock.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProjectID")
	}

	var r0 []*entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Task, error)); ok {
		return returnFunc(ctx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Task); ok {
		r0 = returnFunc(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetByProjectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProjectID'
type MockTaskRepository_GetByProjectID_Call struct {
	*mock.Call
}

// GetByProjectID is a helper method to define mock.On call
//   - ctx
//   - projectID
func (_e *MockTaskRepository_Expecter) GetByProjectID(ctx interface{}, projectID interface{}) *MockTaskRepository_GetByProjectID_Call {
	return &MockTaskRepository_GetByProjectID_Call{Call: _e.mock.On("GetByProjectID", ctx, projectID)}
}

func (_c *MockTaskRepository_GetByProjectID_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockTaskRepository_GetByProjectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetByProjectID_Call) Return(tasks []*entity.Task, err error) *MockTaskRepository_GetByProjectID_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_GetByProjectID_Call) RunAndReturn(run func(ctx context.Context, projectID uuid.UUID) ([]*entity.Task, error)) *MockTaskRepository_GetByProjectID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByStatus provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetByStatus(ctx context.Context, status entity.TaskStatus) ([]*entity.Task, error) {
	ret := _mock.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for GetByStatus")
	}

	var r0 []*entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.TaskStatus) ([]*entity.Task, error)); ok {
		return returnFunc(ctx, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.TaskStatus) []*entity.Task); ok {
		r0 = returnFunc(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.TaskStatus) error); ok {
		r1 = returnFunc(ctx, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByStatus'
type MockTaskRepository_GetByStatus_Call struct {
	*mock.Call
}

// GetByStatus is a helper method to define mock.On call
//   - ctx
//   - status
func (_e *MockTaskRepository_Expecter) GetByStatus(ctx interface{}, status interface{}) *MockTaskRepository_GetByStatus_Call {
	return &MockTaskRepository_GetByStatus_Call{Call: _e.mock.On("GetByStatus", ctx, status)}
}

func (_c *MockTaskRepository_GetByStatus_Call) Run(run func(ctx context.Context, status entity.TaskStatus)) *MockTaskRepository_GetByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.TaskStatus))
	})
	return _c
}

func (_c *MockTaskRepository_GetByStatus_Call) Return(tasks []*entity.Task, err error) *MockTaskRepository_GetByStatus_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_GetByStatus_Call) RunAndReturn(run func(ctx context.Context, status entity.TaskStatus) ([]*entity.Task, error)) *MockTaskRepository_GetByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetByStatuses provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetByStatuses(ctx context.Context, statuses []entity.TaskStatus) ([]*entity.Task, error) {
	ret := _mock.Called(ctx, statuses)

	if len(ret) == 0 {
		panic("no return value specified for GetByStatuses")
	}

	var r0 []*entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entity.TaskStatus) ([]*entity.Task, error)); ok {
		return returnFunc(ctx, statuses)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []entity.TaskStatus) []*entity.Task); ok {
		r0 = returnFunc(ctx, statuses)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []entity.TaskStatus) error); ok {
		r1 = returnFunc(ctx, statuses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetByStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByStatuses'
type MockTaskRepository_GetByStatuses_Call struct {
	*mock.Call
}

// GetByStatuses is a helper method to define mock.On call
//   - ctx
//   - statuses
func (_e *MockTaskRepository_Expecter) GetByStatuses(ctx interface{}, statuses interface{}) *MockTaskRepository_GetByStatuses_Call {
	return &MockTaskRepository_GetByStatuses_Call{Call: _e.mock.On("GetByStatuses", ctx, statuses)}
}

func (_c *MockTaskRepository_GetByStatuses_Call) Run(run func(ctx context.Context, statuses []entity.TaskStatus)) *MockTaskRepository_GetByStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]entity.TaskStatus))
	})
	return _c
}

func (_c *MockTaskRepository_GetByStatuses_Call) Return(tasks []*entity.Task, err error) *MockTaskRepository_GetByStatuses_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_GetByStatuses_Call) RunAndReturn(run func(ctx context.Context, statuses []entity.TaskStatus) ([]*entity.Task, error)) *MockTaskRepository_GetByStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// GetComments provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetComments(ctx context.Context, taskID uuid.UUID) ([]*entity.TaskComment, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 []*entity.TaskComment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.TaskComment, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.TaskComment); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TaskComment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockTaskRepository_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - ctx
//   - taskID
func (_e *MockTaskRepository_Expecter) GetComments(ctx interface{}, taskID interface{}) *MockTaskRepository_GetComments_Call {
	return &MockTaskRepository_GetComments_Call{Call: _e.mock.On("GetComments", ctx, taskID)}
}

func (_c *MockTaskRepository_GetComments_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockTaskRepository_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetComments_Call) Return(taskComments []*entity.TaskComment, err error) *MockTaskRepository_GetComments_Call {
	_c.Call.Return(taskComments, err)
	return _c
}

func (_c *MockTaskRepository_GetComments_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) ([]*entity.TaskComment, error)) *MockTaskRepository_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// GetDependencies provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetDependencies(ctx context.Context, taskID uuid.UUID) ([]*entity.TaskDependency, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetDependencies")
	}

	var r0 []*entity.TaskDependency
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.TaskDependency, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.TaskDependency); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TaskDependency)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetDependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDependencies'
type MockTaskRepository_GetDependencies_Call struct {
	*mock.Call
}

// GetDependencies is a helper method to define mock.On call
//   - ctx
//   - taskID
func (_e *MockTaskRepository_Expecter) GetDependencies(ctx interface{}, taskID interface{}) *MockTaskRepository_GetDependencies_Call {
	return &MockTaskRepository_GetDependencies_Call{Call: _e.mock.On("GetDependencies", ctx, taskID)}
}

func (_c *MockTaskRepository_GetDependencies_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockTaskRepository_GetDependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetDependencies_Call) Return(taskDependencys []*entity.TaskDependency, err error) *MockTaskRepository_GetDependencies_Call {
	_c.Call.Return(taskDependencys, err)
	return _c
}

func (_c *MockTaskRepository_GetDependencies_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) ([]*entity.TaskDependency, error)) *MockTaskRepository_GetDependencies_Call {
	_c.Call.Return(run)
	return _c
}

// GetDependents provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetDependents(ctx context.Context, taskID uuid.UUID) ([]*entity.TaskDependency, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetDependents")
	}

	var r0 []*entity.TaskDependency
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.TaskDependency, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.TaskDependency); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TaskDependency)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetDependents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDependents'
type MockTaskRepository_GetDependents_Call struct {
	*mock.Call
}

// GetDependents is a helper method to define mock.On call
//   - ctx
//   - taskID
func (_e *MockTaskRepository_Expecter) GetDependents(ctx interface{}, taskID interface{}) *MockTaskRepository_GetDependents_Call {
	return &MockTaskRepository_GetDependents_Call{Call: _e.mock.On("GetDependents", ctx, taskID)}
}

func (_c *MockTaskRepository_GetDependents_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockTaskRepository_GetDependents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetDependents_Call) Return(taskDependencys []*entity.TaskDependency, err error) *MockTaskRepository_GetDependents_Call {
	_c.Call.Return(taskDependencys, err)
	return _c
}

func (_c *MockTaskRepository_GetDependents_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) ([]*entity.TaskDependency, error)) *MockTaskRepository_GetDependents_Call {
	_c.Call.Return(run)
	return _c
}

// GetParentTask provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetParentTask(ctx context.Context, taskID uuid.UUID) (*entity.Task, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetParentTask")
	}

	var r0 *entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.Task, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.Task); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetParentTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParentTask'
type MockTaskRepository_GetParentTask_Call struct {
	*mock.Call
}

// GetParentTask is a helper method to define mock.On call
//   - ctx
//   - taskID
func (_e *MockTaskRepository_Expecter) GetParentTask(ctx interface{}, taskID interface{}) *MockTaskRepository_GetParentTask_Call {
	return &MockTaskRepository_GetParentTask_Call{Call: _e.mock.On("GetParentTask", ctx, taskID)}
}

func (_c *MockTaskRepository_GetParentTask_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockTaskRepository_GetParentTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetParentTask_Call) Return(task *entity.Task, err error) *MockTaskRepository_GetParentTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskRepository_GetParentTask_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) (*entity.Task, error)) *MockTaskRepository_GetParentTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusAnalytics provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetStatusAnalytics(ctx context.Context, projectID uuid.UUID) (*entity.TaskStatusAnalytics, error) {
	ret := _mock.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusAnalytics")
	}

	var r0 *entity.TaskStatusAnalytics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.TaskStatusAnalytics, error)); ok {
		return returnFunc(ctx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.TaskStatusAnalytics); ok {
		r0 = returnFunc(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TaskStatusAnalytics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetStatusAnalytics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusAnalytics'
type MockTaskRepository_GetStatusAnalytics_Call struct {
	*mock.Call
}

// GetStatusAnalytics is a helper method to define mock.On call
//   - ctx
//   - projectID
func (_e *MockTaskRepository_Expecter) GetStatusAnalytics(ctx interface{}, projectID interface{}) *MockTaskRepository_GetStatusAnalytics_Call {
	return &MockTaskRepository_GetStatusAnalytics_Call{Call: _e.mock.On("GetStatusAnalytics", ctx, projectID)}
}

func (_c *MockTaskRepository_GetStatusAnalytics_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockTaskRepository_GetStatusAnalytics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetStatusAnalytics_Call) Return(taskStatusAnalytics *entity.TaskStatusAnalytics, err error) *MockTaskRepository_GetStatusAnalytics_Call {
	_c.Call.Return(taskStatusAnalytics, err)
	return _c
}

func (_c *MockTaskRepository_GetStatusAnalytics_Call) RunAndReturn(run func(ctx context.Context, projectID uuid.UUID) (*entity.TaskStatusAnalytics, error)) *MockTaskRepository_GetStatusAnalytics_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusHistory provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetStatusHistory(ctx context.Context, taskID uuid.UUID) ([]*entity.TaskStatusHistory, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusHistory")
	}

	var r0 []*entity.TaskStatusHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.TaskStatusHistory, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.TaskStatusHistory); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TaskStatusHistory)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetStatusHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusHistory'
type MockTaskRepository_GetStatusHistory_Call struct {
	*mock.Call
}

// GetStatusHistory is a helper method to define mock.On call
//   - ctx
//   - taskID
func (_e *MockTaskRepository_Expecter) GetStatusHistory(ctx interface{}, taskID interface{}) *MockTaskRepository_GetStatusHistory_Call {
	return &MockTaskRepository_GetStatusHistory_Call{Call: _e.mock.On("GetStatusHistory", ctx, taskID)}
}

func (_c *MockTaskRepository_GetStatusHistory_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockTaskRepository_GetStatusHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetStatusHistory_Call) Return(taskStatusHistorys []*entity.TaskStatusHistory, err error) *MockTaskRepository_GetStatusHistory_Call {
	_c.Call.Return(taskStatusHistorys, err)
	return _c
}

func (_c *MockTaskRepository_GetStatusHistory_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) ([]*entity.TaskStatusHistory, error)) *MockTaskRepository_GetStatusHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubtasks provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetSubtasks(ctx context.Context, parentTaskID uuid.UUID) ([]*entity.Task, error) {
	ret := _mock.Called(ctx, parentTaskID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubtasks")
	}

	var r0 []*entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Task, error)); ok {
		return returnFunc(ctx, parentTaskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Task); ok {
		r0 = returnFunc(ctx, parentTaskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, parentTaskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetSubtasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubtasks'
type MockTaskRepository_GetSubtasks_Call struct {
	*mock.Call
}

// GetSubtasks is a helper method to define mock.On call
//   - ctx
//   - parentTaskID
func (_e *MockTaskRepository_Expecter) GetSubtasks(ctx interface{}, parentTaskID interface{}) *MockTaskRepository_GetSubtasks_Call {
	return &MockTaskRepository_GetSubtasks_Call{Call: _e.mock.On("GetSubtasks", ctx, parentTaskID)}
}

func (_c *MockTaskRepository_GetSubtasks_Call) Run(run func(ctx context.Context, parentTaskID uuid.UUID)) *MockTaskRepository_GetSubtasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetSubtasks_Call) Return(tasks []*entity.Task, err error) *MockTaskRepository_GetSubtasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_GetSubtasks_Call) RunAndReturn(run func(ctx context.Context, parentTaskID uuid.UUID) ([]*entity.Task, error)) *MockTaskRepository_GetSubtasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskStatistics provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetTaskStatistics(ctx context.Context, projectID uuid.UUID) (*entity.TaskStatistics, error) {
	ret := _mock.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskStatistics")
	}

	var r0 *entity.TaskStatistics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.TaskStatistics, error)); ok {
		return returnFunc(ctx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.TaskStatistics); ok {
		r0 = returnFunc(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TaskStatistics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetTaskStatistics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskStatistics'
type MockTaskRepository_GetTaskStatistics_Call struct {
	*mock.Call
}

// GetTaskStatistics is a helper method to define mock.On call
//   - ctx
//   - projectID
func (_e *MockTaskRepository_Expecter) GetTaskStatistics(ctx interface{}, projectID interface{}) *MockTaskRepository_GetTaskStatistics_Call {
	return &MockTaskRepository_GetTaskStatistics_Call{Call: _e.mock.On("GetTaskStatistics", ctx, projectID)}
}

func (_c *MockTaskRepository_GetTaskStatistics_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockTaskRepository_GetTaskStatistics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetTaskStatistics_Call) Return(taskStatistics *entity.TaskStatistics, err error) *MockTaskRepository_GetTaskStatistics_Call {
	_c.Call.Return(taskStatistics, err)
	return _c
}

func (_c *MockTaskRepository_GetTaskStatistics_Call) RunAndReturn(run func(ctx context.Context, projectID uuid.UUID) (*entity.TaskStatistics, error)) *MockTaskRepository_GetTaskStatistics_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByPriority provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetTasksByPriority(ctx context.Context, priority entity.TaskPriority) ([]*entity.Task, error) {
	ret := _mock.Called(ctx, priority)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByPriority")
	}

	var r0 []*entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.TaskPriority) ([]*entity.Task, error)); ok {
		return returnFunc(ctx, priority)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.TaskPriority) []*entity.Task); ok {
		r0 = returnFunc(ctx, priority)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.TaskPriority) error); ok {
		r1 = returnFunc(ctx, priority)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetTasksByPriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByPriority'
type MockTaskRepository_GetTasksByPriority_Call struct {
	*mock.Call
}

// GetTasksByPriority is a helper method to define mock.On call
//   - ctx
//   - priority
func (_e *MockTaskRepository_Expecter) GetTasksByPriority(ctx interface{}, priority interface{}) *MockTaskRepository_GetTasksByPriority_Call {
	return &MockTaskRepository_GetTasksByPriority_Call{Call: _e.mock.On("GetTasksByPriority", ctx, priority)}
}

func (_c *MockTaskRepository_GetTasksByPriority_Call) Run(run func(ctx context.Context, priority entity.TaskPriority)) *MockTaskRepository_GetTasksByPriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.TaskPriority))
	})
	return _c
}

func (_c *MockTaskRepository_GetTasksByPriority_Call) Return(tasks []*entity.Task, err error) *MockTaskRepository_GetTasksByPriority_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_GetTasksByPriority_Call) RunAndReturn(run func(ctx context.Context, priority entity.TaskPriority) ([]*entity.Task, error)) *MockTaskRepository_GetTasksByPriority_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksByTags provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetTasksByTags(ctx context.Context, tags []string) ([]*entity.Task, error) {
	ret := _mock.Called(ctx, tags)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksByTags")
	}

	var r0 []*entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*entity.Task, error)); ok {
		return returnFunc(ctx, tags)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*entity.Task); ok {
		r0 = returnFunc(ctx, tags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, tags)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetTasksByTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksByTags'
type MockTaskRepository_GetTasksByTags_Call struct {
	*mock.Call
}

// GetTasksByTags is a helper method to define mock.On call
//   - ctx
//   - tags
func (_e *MockTaskRepository_Expecter) GetTasksByTags(ctx interface{}, tags interface{}) *MockTaskRepository_GetTasksByTags_Call {
	return &MockTaskRepository_GetTasksByTags_Call{Call: _e.mock.On("GetTasksByTags", ctx, tags)}
}

func (_c *MockTaskRepository_GetTasksByTags_Call) Run(run func(ctx context.Context, tags []string)) *MockTaskRepository_GetTasksByTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockTaskRepository_GetTasksByTags_Call) Return(tasks []*entity.Task, err error) *MockTaskRepository_GetTasksByTags_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_GetTasksByTags_Call) RunAndReturn(run func(ctx context.Context, tags []string) ([]*entity.Task, error)) *MockTaskRepository_GetTasksByTags_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksWithFilters provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetTasksWithFilters(ctx context.Context, filters entity.TaskFilters) ([]*entity.Task, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksWithFilters")
	}

	var r0 []*entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.TaskFilters) ([]*entity.Task, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, entity.TaskFilters) []*entity.Task); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, entity.TaskFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetTasksWithFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksWithFilters'
type MockTaskRepository_GetTasksWithFilters_Call struct {
	*mock.Call
}

// GetTasksWithFilters is a helper method to define mock.On call
//   - ctx
//   - filters
func (_e *MockTaskRepository_Expecter) GetTasksWithFilters(ctx interface{}, filters interface{}) *MockTaskRepository_GetTasksWithFilters_Call {
	return &MockTaskRepository_GetTasksWithFilters_Call{Call: _e.mock.On("GetTasksWithFilters", ctx, filters)}
}

func (_c *MockTaskRepository_GetTasksWithFilters_Call) Run(run func(ctx context.Context, filters entity.TaskFilters)) *MockTaskRepository_GetTasksWithFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.TaskFilters))
	})
	return _c
}

func (_c *MockTaskRepository_GetTasksWithFilters_Call) Return(tasks []*entity.Task, err error) *MockTaskRepository_GetTasksWithFilters_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_GetTasksWithFilters_Call) RunAndReturn(run func(ctx context.Context, filters entity.TaskFilters) ([]*entity.Task, error)) *MockTaskRepository_GetTasksWithFilters_Call {
	_c.Call.Return(run)
	return _c
}

// GetTasksWithSubtasks provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetTasksWithSubtasks(ctx context.Context, projectID uuid.UUID) ([]*entity.Task, error) {
	ret := _mock.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for GetTasksWithSubtasks")
	}

	var r0 []*entity.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*entity.Task, error)); ok {
		return returnFunc(ctx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*entity.Task); ok {
		r0 = returnFunc(ctx, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetTasksWithSubtasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTasksWithSubtasks'
type MockTaskRepository_GetTasksWithSubtasks_Call struct {
	*mock.Call
}

// GetTasksWithSubtasks is a helper method to define mock.On call
//   - ctx
//   - projectID
func (_e *MockTaskRepository_Expecter) GetTasksWithSubtasks(ctx interface{}, projectID interface{}) *MockTaskRepository_GetTasksWithSubtasks_Call {
	return &MockTaskRepository_GetTasksWithSubtasks_Call{Call: _e.mock.On("GetTasksWithSubtasks", ctx, projectID)}
}

func (_c *MockTaskRepository_GetTasksWithSubtasks_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockTaskRepository_GetTasksWithSubtasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetTasksWithSubtasks_Call) Return(tasks []*entity.Task, err error) *MockTaskRepository_GetTasksWithSubtasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_GetTasksWithSubtasks_Call) RunAndReturn(run func(ctx context.Context, projectID uuid.UUID) ([]*entity.Task, error)) *MockTaskRepository_GetTasksWithSubtasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplateByID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetTemplateByID(ctx context.Context, id uuid.UUID) (*entity.TaskTemplate, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateByID")
	}

	var r0 *entity.TaskTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*entity.TaskTemplate, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *entity.TaskTemplate); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.TaskTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetTemplateByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplateByID'
type MockTaskRepository_GetTemplateByID_Call struct {
	*mock.Call
}

// GetTemplateByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockTaskRepository_Expecter) GetTemplateByID(ctx interface{}, id interface{}) *MockTaskRepository_GetTemplateByID_Call {
	return &MockTaskRepository_GetTemplateByID_Call{Call: _e.mock.On("GetTemplateByID", ctx, id)}
}

func (_c *MockTaskRepository_GetTemplateByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTaskRepository_GetTemplateByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_GetTemplateByID_Call) Return(taskTemplate *entity.TaskTemplate, err error) *MockTaskRepository_GetTemplateByID_Call {
	_c.Call.Return(taskTemplate, err)
	return _c
}

func (_c *MockTaskRepository_GetTemplateByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*entity.TaskTemplate, error)) *MockTaskRepository_GetTemplateByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTemplates provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetTemplates(ctx context.Context, projectID uuid.UUID, includeGlobal bool) ([]*entity.TaskTemplate, error) {
	ret := _mock.Called(ctx, projectID, includeGlobal)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplates")
	}

	var r0 []*entity.TaskTemplate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) ([]*entity.TaskTemplate, error)); ok {
		return returnFunc(ctx, projectID, includeGlobal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) []*entity.TaskTemplate); ok {
		r0 = returnFunc(ctx, projectID, includeGlobal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TaskTemplate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, bool) error); ok {
		r1 = returnFunc(ctx, projectID, includeGlobal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplates'
type MockTaskRepository_GetTemplates_Call struct {
	*mock.Call
}

// GetTemplates is a helper method to define mock.On call
//   - ctx
//   - projectID
//   - includeGlobal
func (_e *MockTaskRepository_Expecter) GetTemplates(ctx interface{}, projectID interface{}, includeGlobal interface{}) *MockTaskRepository_GetTemplates_Call {
	return &MockTaskRepository_GetTemplates_Call{Call: _e.mock.On("GetTemplates", ctx, projectID, includeGlobal)}
}

func (_c *MockTaskRepository_GetTemplates_Call) Run(run func(ctx context.Context, projectID uuid.UUID, includeGlobal bool)) *MockTaskRepository_GetTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *MockTaskRepository_GetTemplates_Call) Return(taskTemplates []*entity.TaskTemplate, err error) *MockTaskRepository_GetTemplates_Call {
	_c.Call.Return(taskTemplates, err)
	return _c
}

func (_c *MockTaskRepository_GetTemplates_Call) RunAndReturn(run func(ctx context.Context, projectID uuid.UUID, includeGlobal bool) ([]*entity.TaskTemplate, error)) *MockTaskRepository_GetTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveDependency provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) RemoveDependency(ctx context.Context, taskID uuid.UUID, dependsOnTaskID uuid.UUID) error {
	ret := _mock.Called(ctx, taskID, dependsOnTaskID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveDependency")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, taskID, dependsOnTaskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_RemoveDependency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveDependency'
type MockTaskRepository_RemoveDependency_Call struct {
	*mock.Call
}

// RemoveDependency is a helper method to define mock.On call
//   - ctx
//   - taskID
//   - dependsOnTaskID
func (_e *MockTaskRepository_Expecter) RemoveDependency(ctx interface{}, taskID interface{}, dependsOnTaskID interface{}) *MockTaskRepository_RemoveDependency_Call {
	return &MockTaskRepository_RemoveDependency_Call{Call: _e.mock.On("RemoveDependency", ctx, taskID, dependsOnTaskID)}
}

func (_c *MockTaskRepository_RemoveDependency_Call) Run(run func(ctx context.Context, taskID uuid.UUID, dependsOnTaskID uuid.UUID)) *MockTaskRepository_RemoveDependency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_RemoveDependency_Call) Return(err error) *MockTaskRepository_RemoveDependency_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_RemoveDependency_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID, dependsOnTaskID uuid.UUID) error) *MockTaskRepository_RemoveDependency_Call {
	_c.Call.Return(run)
	return _c
}

// SearchTasks provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) SearchTasks(ctx context.Context, query string, projectID *uuid.UUID) ([]*entity.TaskSearchResult, error) {
	ret := _mock.Called(ctx, query, projectID)

	if len(ret) == 0 {
		panic("no return value specified for SearchTasks")
	}

	var r0 []*entity.TaskSearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *uuid.UUID) ([]*entity.TaskSearchResult, error)); ok {
		return returnFunc(ctx, query, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *uuid.UUID) []*entity.TaskSearchResult); ok {
		r0 = returnFunc(ctx, query, projectID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*entity.TaskSearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, query, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_SearchTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchTasks'
type MockTaskRepository_SearchTasks_Call struct {
	*mock.Call
}

// SearchTasks is a helper method to define mock.On call
//   - ctx
//   - query
//   - projectID
func (_e *MockTaskRepository_Expecter) SearchTasks(ctx interface{}, query interface{}, projectID interface{}) *MockTaskRepository_SearchTasks_Call {
	return &MockTaskRepository_SearchTasks_Call{Call: _e.mock.On("SearchTasks", ctx, query, projectID)}
}

func (_c *MockTaskRepository_SearchTasks_Call) Run(run func(ctx context.Context, query string, projectID *uuid.UUID)) *MockTaskRepository_SearchTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_SearchTasks_Call) Return(taskSearchResults []*entity.TaskSearchResult, err error) *MockTaskRepository_SearchTasks_Call {
	_c.Call.Return(taskSearchResults, err)
	return _c
}

func (_c *MockTaskRepository_SearchTasks_Call) RunAndReturn(run func(ctx context.Context, query string, projectID *uuid.UUID) ([]*entity.TaskSearchResult, error)) *MockTaskRepository_SearchTasks_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Update(ctx context.Context, task *entity.Task) error {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.Task) error); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx
//   - task
func (_e *MockTaskRepository_Expecter) Update(ctx interface{}, task interface{}) *MockTaskRepository_Update_Call {
	return &MockTaskRepository_Update_Call{Call: _e.mock.On("Update", ctx, task)}
}

func (_c *MockTaskRepository_Update_Call) Run(run func(ctx context.Context, task *entity.Task)) *MockTaskRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.Task))
	})
	return _c
}

func (_c *MockTaskRepository_Update_Call) Return(err error) *MockTaskRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Update_Call) RunAndReturn(run func(ctx context.Context, task *entity.Task) error) *MockTaskRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComment provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) UpdateComment(ctx context.Context, comment *entity.TaskComment) error {
	ret := _mock.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TaskComment) error); ok {
		r0 = returnFunc(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_UpdateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComment'
type MockTaskRepository_UpdateComment_Call struct {
	*mock.Call
}

// UpdateComment is a helper method to define mock.On call
//   - ctx
//   - comment
func (_e *MockTaskRepository_Expecter) UpdateComment(ctx interface{}, comment interface{}) *MockTaskRepository_UpdateComment_Call {
	return &MockTaskRepository_UpdateComment_Call{Call: _e.mock.On("UpdateComment", ctx, comment)}
}

func (_c *MockTaskRepository_UpdateComment_Call) Run(run func(ctx context.Context, comment *entity.TaskComment)) *MockTaskRepository_UpdateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.TaskComment))
	})
	return _c
}

func (_c *MockTaskRepository_UpdateComment_Call) Return(err error) *MockTaskRepository_UpdateComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_UpdateComment_Call) RunAndReturn(run func(ctx context.Context, comment *entity.TaskComment) error) *MockTaskRepository_UpdateComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateParentTask provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) UpdateParentTask(ctx context.Context, taskID uuid.UUID, parentTaskID *uuid.UUID) error {
	ret := _mock.Called(ctx, taskID, parentTaskID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateParentTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *uuid.UUID) error); ok {
		r0 = returnFunc(ctx, taskID, parentTaskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_UpdateParentTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateParentTask'
type MockTaskRepository_UpdateParentTask_Call struct {
	*mock.Call
}

// UpdateParentTask is a helper method to define mock.On call
//   - ctx
//   - taskID
//   - parentTaskID
func (_e *MockTaskRepository_Expecter) UpdateParentTask(ctx interface{}, taskID interface{}, parentTaskID interface{}) *MockTaskRepository_UpdateParentTask_Call {
	return &MockTaskRepository_UpdateParentTask_Call{Call: _e.mock.On("UpdateParentTask", ctx, taskID, parentTaskID)}
}

func (_c *MockTaskRepository_UpdateParentTask_Call) Run(run func(ctx context.Context, taskID uuid.UUID, parentTaskID *uuid.UUID)) *MockTaskRepository_UpdateParentTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_UpdateParentTask_Call) Return(err error) *MockTaskRepository_UpdateParentTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_UpdateParentTask_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID, parentTaskID *uuid.UUID) error) *MockTaskRepository_UpdateParentTask_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status entity.TaskStatus) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.TaskStatus) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockTaskRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx
//   - id
//   - status
func (_e *MockTaskRepository_Expecter) UpdateStatus(ctx interface{}, id interface{}, status interface{}) *MockTaskRepository_UpdateStatus_Call {
	return &MockTaskRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status)}
}

func (_c *MockTaskRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status entity.TaskStatus)) *MockTaskRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.TaskStatus))
	})
	return _c
}

func (_c *MockTaskRepository_UpdateStatus_Call) Return(err error) *MockTaskRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status entity.TaskStatus) error) *MockTaskRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusWithHistory provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) UpdateStatusWithHistory(ctx context.Context, id uuid.UUID, status entity.TaskStatus, changedBy *string, reason *string) error {
	ret := _mock.Called(ctx, id, status, changedBy, reason)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusWithHistory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, entity.TaskStatus, *string, *string) error); ok {
		r0 = returnFunc(ctx, id, status, changedBy, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_UpdateStatusWithHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusWithHistory'
type MockTaskRepository_UpdateStatusWithHistory_Call struct {
	*mock.Call
}

// UpdateStatusWithHistory is a helper method to define mock.On call
//   - ctx
//   - id
//   - status
//   - changedBy
//   - reason
func (_e *MockTaskRepository_Expecter) UpdateStatusWithHistory(ctx interface{}, id interface{}, status interface{}, changedBy interface{}, reason interface{}) *MockTaskRepository_UpdateStatusWithHistory_Call {
	return &MockTaskRepository_UpdateStatusWithHistory_Call{Call: _e.mock.On("UpdateStatusWithHistory", ctx, id, status, changedBy, reason)}
}

func (_c *MockTaskRepository_UpdateStatusWithHistory_Call) Run(run func(ctx context.Context, id uuid.UUID, status entity.TaskStatus, changedBy *string, reason *string)) *MockTaskRepository_UpdateStatusWithHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(entity.TaskStatus), args[3].(*string), args[4].(*string))
	})
	return _c
}

func (_c *MockTaskRepository_UpdateStatusWithHistory_Call) Return(err error) *MockTaskRepository_UpdateStatusWithHistory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_UpdateStatusWithHistory_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status entity.TaskStatus, changedBy *string, reason *string) error) *MockTaskRepository_UpdateStatusWithHistory_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTemplate provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) UpdateTemplate(ctx context.Context, template *entity.TaskTemplate) error {
	ret := _mock.Called(ctx, template)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTemplate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entity.TaskTemplate) error); ok {
		r0 = returnFunc(ctx, template)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_UpdateTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTemplate'
type MockTaskRepository_UpdateTemplate_Call struct {
	*mock.Call
}

// UpdateTemplate is a helper method to define mock.On call
//   - ctx
//   - template
func (_e *MockTaskRepository_Expecter) UpdateTemplate(ctx interface{}, template interface{}) *MockTaskRepository_UpdateTemplate_Call {
	return &MockTaskRepository_UpdateTemplate_Call{Call: _e.mock.On("UpdateTemplate", ctx, template)}
}

func (_c *MockTaskRepository_UpdateTemplate_Call) Run(run func(ctx context.Context, template *entity.TaskTemplate)) *MockTaskRepository_UpdateTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entity.TaskTemplate))
	})
	return _c
}

func (_c *MockTaskRepository_UpdateTemplate_Call) Return(err error) *MockTaskRepository_UpdateTemplate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_UpdateTemplate_Call) RunAndReturn(run func(ctx context.Context, template *entity.TaskTemplate) error) *MockTaskRepository_UpdateTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateProjectExists provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) ValidateProjectExists(ctx context.Context, projectID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, projectID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateProjectExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, projectID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, projectID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, projectID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_ValidateProjectExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateProjectExists'
type MockTaskRepository_ValidateProjectExists_Call struct {
	*mock.Call
}

// ValidateProjectExists is a helper method to define mock.On call
//   - ctx
//   - projectID
func (_e *MockTaskRepository_Expecter) ValidateProjectExists(ctx interface{}, projectID interface{}) *MockTaskRepository_ValidateProjectExists_Call {
	return &MockTaskRepository_ValidateProjectExists_Call{Call: _e.mock.On("ValidateProjectExists", ctx, projectID)}
}

func (_c *MockTaskRepository_ValidateProjectExists_Call) Run(run func(ctx context.Context, projectID uuid.UUID)) *MockTaskRepository_ValidateProjectExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_ValidateProjectExists_Call) Return(b bool, err error) *MockTaskRepository_ValidateProjectExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTaskRepository_ValidateProjectExists_Call) RunAndReturn(run func(ctx context.Context, projectID uuid.UUID) (bool, error)) *MockTaskRepository_ValidateProjectExists_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateTaskExists provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) ValidateTaskExists(ctx context.Context, taskID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateTaskExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_ValidateTaskExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateTaskExists'
type MockTaskRepository_ValidateTaskExists_Call struct {
	*mock.Call
}

// ValidateTaskExists is a helper method to define mock.On call
//   - ctx
//   - taskID
func (_e *MockTaskRepository_Expecter) ValidateTaskExists(ctx interface{}, taskID interface{}) *MockTaskRepository_ValidateTaskExists_Call {
	return &MockTaskRepository_ValidateTaskExists_Call{Call: _e.mock.On("ValidateTaskExists", ctx, taskID)}
}

func (_c *MockTaskRepository_ValidateTaskExists_Call) Run(run func(ctx context.Context, taskID uuid.UUID)) *MockTaskRepository_ValidateTaskExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTaskRepository_ValidateTaskExists_Call) Return(b bool, err error) *MockTaskRepository_ValidateTaskExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockTaskRepository_ValidateTaskExists_Call) RunAndReturn(run func(ctx context.Context, taskID uuid.UUID) (bool, error)) *MockTaskRepository_ValidateTaskExists_Call {
	_c.Call.Return(run)
	return _c
}
