all: false                                # Không generate tất cả interface toàn repo (chỉ những cái bạn định nghĩa bên dưới)
dir: '{{.InterfaceDir}}'                  # Giữ nguyên, mockery sẽ tự lấy dir từ gói tương ứng trong `packages:`
filename: '{{.InterfaceName | snakecase }}_mock.go'
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.InterfaceName}}Mock'      # Tên struct sẽ là `OrderServiceMock`
pkgname: '{{.SrcPackageName}}'            # Giữ nguyên tên package như trong source
recursive: false
template: testify
require-template-schema-exists: false

packages:
  github.com/auto-devs/auto-devs/internal/usecase:
    config:
      all: true
    interfaces:
      ProjectUsecase:
      NotificationUsecase:
  github.com/auto-devs/auto-devs/internal/repository:
    config:
      all: true
    interfaces:
      TaskRepository:
      ProjectRepository: