// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/auto-devs/auto-devs/config"
	"github.com/auto-devs/auto-devs/internal/repository"
	"github.com/auto-devs/auto-devs/internal/repository/postgres"
	"github.com/auto-devs/auto-devs/internal/usecase"
	"github.com/auto-devs/auto-devs/pkg/database"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeApp builds the entire dependency tree
func InitializeApp() (*App, error) {
	configConfig := config.Load()
	gormDB, err := ProvideGormDB(configConfig)
	if err != nil {
		return nil, err
	}
	projectRepository := postgres.NewProjectRepository(gormDB)
	taskRepository := postgres.NewTaskRepository(gormDB)
	auditRepository := postgres.NewAuditRepository(gormDB)
	auditService := ProvideAuditService(auditRepository)
	projectUsecase := ProvideProjectUsecase(projectRepository, auditService)
	notificationUsecase := usecase.NewNotificationUsecase()
	taskUsecase := ProvideTaskUsecase(taskRepository, projectRepository, notificationUsecase)
	app := NewApp(configConfig, gormDB, projectRepository, taskRepository, auditRepository, auditService, projectUsecase, taskUsecase, notificationUsecase)
	return app, nil
}

// wire.go:

// ProviderSet is the Wire provider set for the entire application
var ProviderSet = wire.NewSet(config.Load, ProvideGormDB, postgres.NewProjectRepository, postgres.NewTaskRepository, postgres.NewAuditRepository, usecase.NewNotificationUsecase, ProvideAuditService,
	ProvideProjectUsecase,
	ProvideTaskUsecase,
)

// App represents the initialized application with all dependencies
type App struct {
	Config              *config.Config
	GormDB              *database.GormDB
	ProjectRepo         repository.ProjectRepository
	TaskRepo            repository.TaskRepository
	AuditRepo           repository.AuditRepository
	AuditService        usecase.AuditService
	ProjectUsecase      usecase.ProjectUsecase
	TaskUsecase         usecase.TaskUsecase
	NotificationUsecase usecase.NotificationUsecase
}

// NewApp creates a new App instance
func NewApp(
	cfg *config.Config,
	gormDB *database.GormDB,
	projectRepo repository.ProjectRepository,
	taskRepo repository.TaskRepository,
	auditRepo repository.AuditRepository,
	auditService usecase.AuditService,
	projectUsecase usecase.ProjectUsecase,
	taskUsecase usecase.TaskUsecase,
	notificationUsecase usecase.NotificationUsecase,
) *App {
	return &App{
		Config:              cfg,
		GormDB:              gormDB,
		ProjectRepo:         projectRepo,
		TaskRepo:            taskRepo,
		AuditRepo:           auditRepo,
		AuditService:        auditService,
		ProjectUsecase:      projectUsecase,
		TaskUsecase:         taskUsecase,
		NotificationUsecase: notificationUsecase,
	}
}

// ProvideGormDB provides a GORM database connection
func ProvideGormDB(cfg *config.Config) (*database.GormDB, error) {
	return database.NewGormDB(cfg)
}

// ProvideAuditService provides an AuditService instance
func ProvideAuditService(auditRepo repository.AuditRepository) usecase.AuditService {
	return usecase.NewAuditService(auditRepo)
}

// ProvideProjectUsecase provides a ProjectUsecase instance
func ProvideProjectUsecase(projectRepo repository.ProjectRepository, auditService usecase.AuditService) usecase.ProjectUsecase {
	return usecase.NewProjectUsecase(projectRepo, auditService)
}

// ProvideTaskUsecase provides a TaskUsecase instance
func ProvideTaskUsecase(taskRepo repository.TaskRepository, projectRepo repository.ProjectRepository, notificationUsecase usecase.NotificationUsecase) usecase.TaskUsecase {
	return usecase.NewTaskUsecase(taskRepo, projectRepo, notificationUsecase)
}
