import type { Task } from '@/types/task'
import { ChevronDown, RefreshCcw } from 'lucide-react'
import { useGetTaskPlans } from '@/hooks/use-tasks'
import { Badge } from '@/components/ui/badge'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from '@/components/ui/collapsible'
import { Button } from '../ui/button'
import { PlanPreview } from './plan-preview'

interface PlanReviewProps {
  task: Task
  onPlanUpdate?: (updatedTask: Task) => void
  onStatusChange?: (taskId: string, newStatus: Task['status']) => void
}

export function PlanReview({ task }: PlanReviewProps) {
  const { data, isLoading, error, refetch } = useGetTaskPlans(task.id)
  const plans = data?.plans

  if (isLoading) {
    return (
      <Card className='w-full'>
        <CardContent className='flex flex-col items-center justify-center py-8'>
          <div className='mb-4 h-12 w-12 animate-spin rounded-full border-4 border-gray-300 border-t-blue-600' />
          <p className='text-sm text-gray-500'>Loading plans...</p>
        </CardContent>
      </Card>
    )
  }

  if (error) {
    return (
      <Card className='w-full'>
        <CardContent className='flex flex-col items-center justify-center py-8'>
          <FileText className='mb-4 h-12 w-12 text-red-400' />
          <h3 className='mb-2 text-lg font-medium text-red-600'>
            Error Loading Plans
          </h3>
          <p className='text-sm text-red-500'>{error}</p>
          <Button onClick={() => refetch()}>Retry</Button>
        </CardContent>
      </Card>
    )
  }

  if (!plans || plans.length === 0) {
    return (
      <Card className='w-full'>
        <CardContent className='flex flex-col items-center justify-center py-8'>
          <FileText className='mb-4 h-12 w-12 text-gray-400' />
          <h3 className='mb-2 text-lg font-medium'>No Plans Available</h3>
          <p className='max-w-md text-center text-sm text-gray-500'>
            This task doesn't have any plans yet. Plans will appear here once
            they're generated by the AI planning process.
          </p>
          <Button onClick={() => refetch()}>Refetch</Button>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card className='w-full'>
      <CardHeader className='mb-4 flex flex-row items-center justify-between'>
        <div className='flex flex-col'>
          <CardTitle>Plan Review</CardTitle>
          <CardDescription>
            Review the plans for this task. The most recent plan appears first.
          </CardDescription>
        </div>
        <div className='flex justify-end'>
          <Button variant='outline' onClick={() => refetch()}>
            <RefreshCcw className='mr-2 h-4 w-4' />
            Refetch
          </Button>
        </div>
      </CardHeader>
      <CardContent className='space-y-4'>
        {plans.map((plan, index) => (
          <Collapsible key={plan.id} defaultOpen={index === 0}>
            <CollapsibleTrigger className='flex w-full items-center justify-between rounded-lg border p-4 hover:bg-gray-50'>
              <div className='flex w-full items-center justify-between gap-3'>
                <div className='text-left'>
                  <div className='font-medium'>Plan {plans.length - index}</div>
                  <div className='text-sm text-gray-500'>
                    Created {new Date(plan.created_at).toLocaleDateString()} at{' '}
                    {new Date(plan.created_at).toLocaleTimeString()}
                  </div>
                </div>
                {plan.status && (
                  <Badge variant='outline' className='ml-2'>
                    {plan.status}
                  </Badge>
                )}
              </div>
              <ChevronDown className='h-4 w-4 transition-transform duration-200 group-data-[state=open]:rotate-180' />
            </CollapsibleTrigger>
            <CollapsibleContent className='px-4 pb-4'>
              <div className='mt-4 rounded-lg border bg-gray-50 p-4'>
                <PlanPreview content={plan.content} className='w-full' />
              </div>
            </CollapsibleContent>
          </Collapsible>
        ))}
      </CardContent>
    </Card>
  )
}
