import type { Task } from '@/types/task'
import { FileText } from 'lucide-react'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { PlanPreview } from './plan-preview'

interface PlanReviewProps {
  task: Task
  onPlanUpdate?: (updatedTask: Task) => void
  onStatusChange?: (taskId: string, newStatus: Task['status']) => void
}

export function PlanReview({ task }: PlanReviewProps) {
  const firstPlan = task.plans && task.plans.length > 0 ? task.plans[0] : null
  const planContent = firstPlan?.content || ''

  const hasPlan = Boolean(planContent?.trim())

  if (!hasPlan) {
    return (
      <Card className='w-full'>
        <CardContent className='flex flex-col items-center justify-center py-8'>
          <FileText className='mb-4 h-12 w-12 text-gray-400' />
          <h3 className='mb-2 text-lg font-medium'>No Plan Available</h3>
          <p className='max-w-md text-center text-sm text-gray-500'>
            This task doesn't have a plan yet. The plan will appear here once
            it's generated by the AI planning process.
          </p>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card className='w-full'>
      <CardHeader>
        <CardTitle>Plan Review</CardTitle>
        <CardDescription>
          Review the plan for this task and approve it for implementation.
        </CardDescription>
      </CardHeader>
      <CardContent className='flex flex-col items-center justify-center'>
        <PlanPreview content={planContent} className='w-full' />
      </CardContent>
    </Card>
  )
}
